### ISSUE TITLE
All IDA Pro links

### ISSUE THREAD

**Issue by VanHoevenTR** [IDALeaker/IDA-Pro-Leak#1]
IDA Pro 7.7 SP1 Windows (Portable) + Decompilers x86, x64, ARM64 + Old hexrays fix.zip
https://siasky.net/EAAsRXKWLbLdZoso0pQuCAqeUz4o6FKE-yRxzO1kha7YqQ

IDA Pro 7.6 SP1 Windows (Portable) + Decompilers x86, x64, ARM, ARM64, MIPS + Tools.zip
https://siasky.net/EAD1npvivtZUsTRSBmeFJgEj24c-9SRLBdWkgtN0aV6uog

IDA Pro 7.5.20.1028 SP3 Windows (Portable) + All decompilers + SDK + Tools.zip
https://siasky.net/EAAJXw0nVGduvN56G49FAC5jMtG2ZNoAJ0Pv7Ti1iXlP7g

IDA Pro 7.3 Windows + SDK & Tools + Patched Decompiler.zip
https://siasky.net/EACmqz8FCpV4ExrOeWV0bCmVCvxOPUeiansxE9Jci1gwFQ

IDA Pro 7.2 Windows + SDK (No decompiler).zip
https://siasky.net/CABdlZAeNxYJomchZulvibupzZHrWNn3r2rps54DC0GNiA

IDA Pro 7.0 Windows & macOS + SDK & Plugins + All Decompilers.zip
https://siasky.net/GAB_XUaXdFqkt8CxLdg9jEI1QYsVSDShnhaNS2n7uJJdgw

IDA Pro 6.6 Windows + SDK.zip
https://siasky.net/CAApoBsXkBX4gtQizepYrq5ZXDVtQ8aH3_6QOPMKxjMxaQ

IDA Pro 6.8 Windows + SDK.zip
https://siasky.net/CACmQ7m6j-gvU5nsl5bBAdFRC45PnRj-yzAO721peW8hNQ

More version (Use [Tor browser](https://www.torproject.org/download/) to connect to onion url)
http://fckilfkscwusoopguhi7i6yg3l6tknaz7lrumvlhg5mvtxzxbbxlimid.onion/

**Comment by IDALeaker** [comment]
Thanks! I'm going to add these to the releases!

**Comment by VilotStar** [comment]
The onion is down, does anyone have any idea if its coming back?

**Comment by jensk-dev** [comment]
7.7 SP1 doesn't seem to be working

**Comment by polybiusproxy** [comment]
> aHR0cHM6Ly93d3cuYXQ0cmUubmV0L2YvdGhyZWFkLTI5OTcuaHRtbA==

you have to sign up to access the .txt file
please upload it here

**Comment by mach-xnu** [comment]
Never found the a working version for apple silicon and generally macOS.
Has anyone found anything?

**Comment by mach-xnu** [comment]
Btw, I even got the educational license from my college but does not work on my m1 mac 🤨
```aHR0cHM6Ly93d3cuZHItZmFyZmFyLmNvbS9oZXgtcmF5cy1pZGEtcHJvZmVzc2lvbmFsLWFkdmFuY2VkLWFuZC1kZWNvbXBpbGVyLWZ1bGwtYWN0aXZhdGVkLw==```

**Comment by mach-xnu** [comment]
@VanHoevenTR I see. Oh, that’s just a base64-encoded url, not a license.

**Comment by VilotStar** [comment]
I mean I wouldn't use it as the TOR link works now which is more trustworthy

**Comment by FrannDzs** [comment]
@mach-xnu 
The link you provided does not work.
The link I previously provided in base64 is the mirror of the one you provided. It has been down for a while.

**Comment by Oct4Pie** [comment]
@VanHoevenTR @VilotStar I mean I am using it on a windows VM. It is actually the original version of the one @FrannDzs posted earlier but seems to be down now.
> aHR0cHM6Ly93d3cuYXQ0cmUubmV0L2YvdGhyZWFkLTI5OTcuaHRtbA==

Dr. FarFar is the guy behind them.

Also, you can check these:
 https://t.me/at4redotnet
 https://t.me/Dr_FarFar_Channel
 https://t.me/IDAProAll
 https://t.me/IDA_Pro
 
 @FrannDzs
I agree. You cannot trust anything you find on the internet. I am in a bad situation because I need to follow a schedule and my license wasn't working properly. I still use a VM and activate the firewall just in case.

**Comment by Oct4Pie** [comment]
@VanHoevenTR @VilotStar I mean I am using it on a windows VM. It is actually the original version of the one @FrannDzs posted earlier but seems to be down now.

aHR0cHM6Ly93d3cuYXQ0cmUubmV0L2YvdGhyZWFkLTI5OTcuaHRtbA==
Dr. FarFar is the guy behind them.

Also, you can check these:
https://t.me/at4redotnet
https://t.me/Dr_FarFar_Channel
https://t.me/IDAProAll
https://t.me/IDA_Pro

@FrannDzs
I agree. You cannot trust anything you find on the internet. I am in a bad situation because I need to follow a schedule and my license wasn't working properly. I still use a VM and activate the firewall just in case.

**Comment by VilotStar** [comment]
@mach-xnu
The fact that you are using onion.pet to access onion links just disproves what you said lol, plus if you checksum the files on the onion link vs the IDA website, (the trial of 8.0 and onion 8.0 trial) they are the same, of course the patched versions are different but barely different which can be verified using a disassembler

**Comment by FrannDzs** [comment]
>The fact that you are using onion.pet to access onion links just disproves what you said lol, plus if you checksum the files on the onion link vs the IDA website, (the trial of 8.0 and onion 8.0 trial) they are the same, of course the patched versions are different but barely different which can be verified using a disassembler

That does not mean that I use .pet.

You can check with a disassembler all you want but there are things that hide very well. I don't know what the limits are in this, there are some people that go beyond everything, so there could be something in your PC for a long time and you are not even aware of it.

**Comment by VilotStar** [comment]
> >The fact that you are using onion.pet to access onion links just disproves what you said lol, plus if you checksum the files on the onion link vs the IDA website, (the trial of 8.0 and onion 8.0 trial) they are the same, of course the patched versions are different but barely different which can be verified using a disassembler
> 
> 
> 
> That does not mean that I use .pet.
> 
> 
> 
> You can check with a disassembler all you want but there are things that hide very well. I don't know what the limits are in this, there are some people that go beyond everything, so there could be something in your PC for a long time and you are not even aware of it.

Highly doubt there would be anything that hidden, but for the sake of this being GitHub and not DMs I'm going to try not to continue this argument, although I would love to in other situations.

**Comment by twokilohertz** [comment]
> @polybiusproxy @jensk-dev @VanHoevenTR @VilotStar @twokilohertz The caramelised onion is back 😍 Now first of all make a mirror of this so that we never again mourn its disappearance. Enjoy!

I've actually found a torrent which has archived the site. Base64 encoded again.

`bWFnbmV0Oj94dD11cm46YnRpaDpiZTI4MDhhNTk5MTNlMDBmOTViNjk2NGZlZDI3N2QzYTUzMGNj
ZWIxJnh0PXVybjpidG1oOjEyMjAyOTI0Y2JjZGYxMGM2MmU5MGY2YjIwZGZlNjRjZDc5NDhlY2E4
NDc2ZmU3NzBiMTBkYzJhODJhOTFiY2JlOTFjJmRuPUlEQSUyMFBybyUyME9uaW9uJTIwQXJjaGl2
ZSUyMDIwMDcxOSZ0cj11ZHAlM2ElMmYlMmZ0cmFja2VyLm9wZW50cmFja3Iub3JnJTNhMTMzNyUy
ZmFubm91bmNlJnRyPXVkcCUzYSUyZiUyZjkucmFyYmcuY29tJTNhMjgxMCUyZmFubm91bmNlJnRy
PXVkcCUzYSUyZiUyZnRyYWNrZXIub3BlbmJpdHRvcnJlbnQuY29tJTNhNjk2OSUyZmFubm91bmNl
JnRyPWh0dHAlM2ElMmYlMmZ0cmFja2VyLm9wZW5iaXR0b3JyZW50LmNvbSUzYTgwJTJmYW5ub3Vu
Y2UmdHI9aHR0cHMlM2ElMmYlMmZvcGVudHJhY2tlci5pMnAucm9ja3MlM2E0NDMlMmZhbm5vdW5j
ZSZ0cj11ZHAlM2ElMmYlMmZvcGVuLnRyYWNrZXIuY2wlM2ExMzM3JTJmYW5ub3VuY2UmdHI9dWRw
JTNhJTJmJTJmb3Blbi5zdGVhbHRoLnNpJTNhODAlMmZhbm5vdW5jZSZ0cj11ZHAlM2ElMmYlMmZ0
cmFja2VyLnRvcnJlbnQuZXUub3JnJTNhNDUxJTJmYW5ub3VuY2UmdHI9dWRwJTNhJTJmJTJmdHJh
Y2tlci50aW55LXZwcy5jb20lM2E2OTY5JTJmYW5ub3VuY2UmdHI9dWRwJTNhJTJmJTJmZXhvZHVz
LmRlc3luYy5jb20lM2E2OTY5JTJmYW5ub3VuY2UmdHI9dWRwJTNhJTJmJTJmdHJhY2tlci5tb2Vr
aW5nLm1lJTNhNjk2OSUyZmFubm91bmNlJnRyPXVkcCUzYSUyZiUyZnRyYWNrZXIuZGxlci5vcmcl
M2E2OTY5JTJmYW5ub3VuY2UmdHI9dWRwJTNhJTJmJTJmdHJhY2tlci4weC50ZiUzYTY5NjklMmZh
bm5vdW5jZSZ0cj11ZHAlM2ElMmYlMmZvcGVuLmRlbW9uaWkuY29tJTNhMTMzNyUyZmFubm91bmNl
JnRyPXVkcCUzYSUyZiUyZm1vdmllcy56c3cuY2ElM2E2OTY5JTJmYW5ub3VuY2UmdHI9dWRwJTNh
JTJmJTJmZXhwbG9kaWUub3JnJTNhNjk2OSUyZmFubm91bmNlJnRyPWh0dHBzJTNhJTJmJTJmdHJh
Y2tlci5uYW5vaGEub3JnJTNhNDQzJTJmYW5ub3VuY2UmdHI9aHR0cHMlM2ElMmYlMmZ0cmFja2Vy
LmxvZ2lybC5tb2UlM2E0NDMlMmZhbm5vdW5jZSZ0cj1odHRwcyUzYSUyZiUyZnRyYWNrZXIubGls
aXRocmF3cy5vcmclM2E0NDMlMmZhbm5vdW5jZSZ0cj1odHRwJTNhJTJmJTJmdHJhY2tlcjEuYnQu
bW9hY2suY28ua3IlM2E4MCUyZmFubm91bmNlCg==`

**Comment by VilotStar** [comment]
Already have the entire site downloaded and hosted on another hidden service, although I might make a torrent and a IPFS
